spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:29092}
      bindings:
        prices-in-0:
          destination: com.ivanfranchin.bitcoin.api.price
          group: bitcoinClientGroup
    function:
      definition: prices # https://github.com/spring-cloud/spring-cloud-function/issues/942
  sleuth:
    sampler:
      probability: 1.0

management:
  endpoints:
    web:
      exposure.include: beans, env, health, info, metrics, mappings
  endpoint:
    health:
      show-details: always
